### ISSUE TITLE
Why the images are always be rendered first

### ISSUE THREAD

**Issue by vinhtq** [Exilz/react-native-render-html#7]
I have html content with images, although they are at the bottom of the content.
But during rendering, they will be put on top

**Comment by Exilz** [comment]
Hi @vinhtq ,
this is a known bug.

I think it's because of a security we integrated to make sure `<Image />` components aren't rendered inside `<Text>`.
It used to make android crash, I'm not sure, but I think it's been resolved in the latest react-native versions.

Once I have some time, I'll try to disable this "safety" to see if it still does it.

**Comment by Liqiankun** [comment]
Image is blank!

**Comment by Exilz** [comment]
With the latest version, images that are at the top of the content will be rendered properly, even if they are within `Text` component.
@Liqiankun I guess you're having a problem of network of some kind (ATS on iOS typically...), it's not related to this issue anyway.
